# Generated by Django 2.1.5 on 2020-08-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200824_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='first_visit',
        ),
        migrations.RemoveField(
            model_name='page',
            name='last_visit',
        ),
    ]
